name: Propose Release

on:
  workflow_dispatch:

jobs:
  propose_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Get version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create a new branch for the PR
        run: |
          git checkout -b release-${{ env.VERSION }}
          git push origin release-${{ env.VERSION }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Release ${{ env.VERSION }}"
          body: "Human review requested!"
          base: dev
          branch: release-${{ env.VERSION }}
