name: Stable Release
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish_stable:
    uses: TigreGotico/gh-automations/.github/workflows/publish-stable.yml@master
    with:
      branch: 'master'
      version_file: 'version.py'
      setup_py: 'setup.py'
      update_changelog: true
      publish_release: true
      publish_pypi: false
      changelog_max_issues: 100
      rebase_dev: true

  rebase_dev:
    needs: publish_stable
    if: success()  # Ensure this job only runs if the previous job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0  # Fetch full history for rebase

      - name: Sync dev with master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin dev
          git push origin dev --force