name: Stable Release
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish_stable:
    uses: TigreGotico/gh-automations/.github/workflows/publish-stable.yml@master
    with:
      branch: 'master'
      version_file: 'version.py'
      setup_py: 'setup.py'
      update_changelog: true
      publish_release: true
      publish_pypi: false
      changelog_max_issues: 100
      rebase_dev: true

  reset_dev:
    needs: publish_stable
    if: success()  # Ensure this job only runs if the previous job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
