name: Rebase Dev onto Master

on:
  push:
    branches:
      - master

jobs:
  rebase_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0  # Fetch full history for rebase

      - name: Checkout dev branch
        run: |
          git fetch origin dev
          git checkout dev

      - name: Rebase dev onto master
        run: |
          git rebase origin/master

      - name: Push rebased dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin dev --force
