name: Rebase Dev onto Master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  rebase_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0  # Fetch full history for rebase

      - name: Sync dev with master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin dev
          git push origin dev --force
